// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.java.vogon {
    exports com.mastfrog.java.vogon;

    // Inferred from source scan
    requires com.mastfrog.function;

    // Inferred from source scan

    // Transitive detected by source scan
    requires com.mastfrog.streams;
    requires java.compiler;
    requires java.logging;

    // Inferred from test-source-scan
    requires transitive org.junit.jupiter.api;

}
