// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.annotation.tools {
    exports com.mastfrog.annotation;
    exports com.mastfrog.annotation.processor;
    exports com.mastfrog.annotation.registries;
    exports com.mastfrog.annotation.validation;

    // Inferred from source scan
    requires com.mastfrog.abstractions;

    // Inferred from source scan

    // Sibling com.mastfrog/util-collections-3.0.0-dev
    requires com.mastfrog.collections;

    // Inferred from source scan

    // Sibling com.mastfrog/function-3.0.0-dev
    requires com.mastfrog.function;

    // Sibling com.mastfrog/java-vogon-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.java.vogon;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Sibling com.mastfrog/predicates-3.0.0-dev
    requires com.mastfrog.predicates;

    // Inferred from source scan
    requires com.mastfrog.strings;
    requires java.compiler;
    requires java.logging;
}
