open module com.mastfrog.annotation.tools {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.annotation;
    exports com.mastfrog.annotation.processor;
    exports com.mastfrog.annotation.registries;
    exports com.mastfrog.annotation.validation;
    requires transitive com.mastfrog.function;
    requires transitive com.mastfrog.java.vogon;
    requires transitive com.mastfrog.predicates;
    requires transitive com.mastfrog.util.collections;
    requires transitive com.mastfrog.util.strings;
    requires java.compiler;
    requires java.logging;

    // derived from org.netbeans.api/org-netbeans-api-annotations-common-RELEASE126:provided in org/netbeans/api/org-netbeans-api-annotations-common/RELEASE126/org-netbeans-api-annotations-common-RELEASE126.pom
    requires org.netbeans.api.annotations.common.RELEASE126;

    // derived from org.netbeans.api/org-openide-filesystems-RELEASE126 in org/netbeans/api/org-openide-filesystems/RELEASE126/org-openide-filesystems-RELEASE126.pom
    requires org.openide.filesystems.RELEASE126;
    
//    opens org.openide.filesystems.api to com.mastfrog.annotation.processors;
//    opens org.openide.filesystems.spi to com.mastfrog.annotation.processors;

    // derived from org.netbeans.api/org-openide-util-lookup-RELEASE126 in org/netbeans/api/org-openide-util-lookup/RELEASE126/org-openide-util-lookup-RELEASE126.pom
//    requires org.openide.util.lookup.RELEASE126;

}
